### ISSUE TITLE
github.com/crgimenes/goconfig/toml does not exist

### ISSUE THREAD

**Issue by c-nv-s** [crgimenes/pgfs#1]
just tried to test your program but it looks like one of the dependencies does not exist.

**Comment by crgimenes** [comment]
man, 5 years!
I did a quick fix and now the configuration should work correctly but using ini files.
FUSE doesn't seem to support macOS anymore, on Linux it probably works ok but I can't test it right now.

**Comment by c-nv-s** [comment]
maybe 5 years old but doesn't mean it still isn't useful for people.
I'm using debian not mac. re-pulled and retested
```
# github.com/crgimenes/pgfs/filesystem
filesystem/filesystem.go:129:8: undefined: fuse.LocalVolume
filesystem/filesystem.go:130:8: undefined: fuse.VolumeName
filesystem/filesystem.go:188:6: c.Ready undefined (type *fuse.Conn has no field or method Ready)
filesystem/filesystem.go:189:10: c.MountError undefined (type *fuse.Conn has no field or method MountError)
```

**Comment by c-nv-s** [comment]
no real urgency for this, so you can test it in your own time, but it would really useful for me to get this working :-)
also if you consider adding write support in the future that would be magic!

**Comment by crgimenes** [comment]
I made several small corrections and now it works.

<img width="751" alt="cat" src="https://github.com/crgimenes/pgfs/assets/834772/916f349d-c7b9-4264-b480-0f3cd45bc9e0">

I still have a lot to work out, like it only works on linux and the massive performance problem with large tables.
To write, it's another set of problems, but who knows one day. I'll try to take a look at this system, I had forgotten how nice it is to open a table directly from cat, grap, etc.

I'll leave the issue open for now, feel free to send your contributions as well. ;)
